---
name: Security Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Install yamllint
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install yamllint

    - name: Run yamllint
      run: yamllint .github/workflows/*.yml
